Fix missing win32 library not detected by py2exe
pywintypes.com_error: -2147221021 'Operation unavailable' / 'Operación no disponible'

```
wsaa-cli.exe /Automate
Encodign in cp1252
pythoncom error: PythonCOM Server - The 'win32com.server.policy' module could not be loaded.

ModuleNotFoundError: No module named 'win32com.server.policy'
pythoncom error: CPyFactory::CreateInstance failed to create instance. (80004005)
```

Also warning with network drives and permissions issues: 'Class not registered'
pywintypes.com_error: (-2147221164, 'Clase no registrada', None, None)