Only run release on original repository, not forks
This avoids errors with dependabot PR:
```
Run marvinpinto/action-automatic-releases@latest
Initializing the Automatic Releases action
Determining release tags
Retrieving commit history
Generating changelog
Generating release tag
  Attempting to create or update release tag "beta"
  Could not create new tag "refs/tags/beta" (Resource not accessible by integration) therefore updating existing tag "tags/beta"
  Error: Resource not accessible by integration
```

Signed-off-by: Nicolás Sandoval <nicolassandovalunm@gmail.com>