WSAA: py3k m2crypto BIO expect bytes
  File "/home/reingart/.local/lib/python3.8/site-packages/M2Crypto/BIO.py", line 186, in __init__
    raise TypeError(
TypeError: data must be bytes or None, not str